import Foundation

/// Pasteboard type conventions from nspasteboard.org (cited in PRD appendix)
/// plus SafeClip's own marker type.
///
/// These are the backbone of the password-safety story:
///  - Password managers (1Password, Bitwarden, KeePassXC, …) mark secrets with
///    `ConcealedType`. SafeClip honours that mark: such items are flagged
///    `.concealed`, their previews are masked in the panel, and pasting them
///    re-applies the mark so *other* clipboard managers skip them too.
///  - `TransientType` marks data not meant to be stored (autofill internals,
///    temporary transforms). SafeClip never stores transient pasteboards.
///  - `safeClipMarker` is written on every SafeClip paste so the monitor
///    recognises its own writes and never re-captures them — without this, a
///    burned item would resurrect itself the moment it is pasted.
public enum PasteboardConvention {
    public static let concealed = "org.nspasteboard.ConcealedType"
    public static let transient = "org.nspasteboard.TransientType"
    public static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    public static let source = "org.nspasteboard.source"
    public static let safeClipMarker = "com.mudit.safeclip.self-write"
}
